---
name: Build all RPMs
on:
  push:
    branches-ignore:
      - main
  workflow_call:
jobs:
  build:
    name: Build all RPMs in a Fedora container
    runs-on: ubuntu-20.04
    steps:
      - name: Check space before clean up
        run: df -h
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          # The root file system needs space for the container.
          root-reserve-mb: 15120
          temp-reserve-mb: 5120
          # Lower the swap size to 1 GB.
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      - name: Check space after clean up
        run: df -h
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd $GITHUB_WORKSPACE
      - name: Create a container
        run: docker run -d -v $(pwd):/root --name fedora38 fedora:38 sleep infinity
      - name: Build all of the RPMs
        run: docker exec fedora38 /root/build_all.sh
      - name: Check space at the end
        run: df -h
