---
name: Test legendary
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'legendary/**'
jobs:
  test:
    name: Test legendary RPM build
    runs-on: ubuntu-22.04
    container:
      image: fedora:41
    steps:
      - uses: actions/checkout@v3
      - name: Install RPM build dependencies
        run: dnf install -y copr-cli rpm-build rpmdevtools
      - name: Create the necessary RPM build directories
        run: mkdir -p ~/rpmbuild/SOURCES/
      - name: Copy internal source files
        run: cp ${GITHUB_WORKSPACE}/legendary/* ~/rpmbuild/SOURCES/
      - name: Download external source files
        run: spectool -g -R ${GITHUB_WORKSPACE}/legendary/*.spec
      - name: Build the source RPM
        run: rpmbuild -bs ${GITHUB_WORKSPACE}/legendary/*.spec
      - name: Install the DNF build dependencies plugin
        run: dnf -y install 'dnf-command(builddep)'
      - name: Install the required build dependencies.
        run: dnf builddep -y ${GITHUB_WORKSPACE}/legendary/legendary.spec
      - name: Build the binary RPM
        run: rpmbuild -bb ${GITHUB_WORKSPACE}/legendary/legendary.spec
      - name: Install RPMs
        run: dnf -y install ~/rpmbuild/RPMS/*/*.rpm
