---
name: Upload playtron-os-scripts source RPM
on:
  push:
    branches:
      - main
    paths:
      - 'playtron-os-scripts/**'
jobs:
  upload:
    name: Upload playtron-os-scripts source RPM to Fedora Copr
    runs-on: ubuntu-20.04
    container:
      image: fedora:38
    env:
      FEDORA_COPR_LOGIN: ${{ secrets.FEDORA_COPR_LOGIN }}
      FEDORA_COPR_TOKEN: ${{ secrets.FEDORA_COPR_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install RPM build dependencies
        run: dnf install -y copr-cli rpm-build rpmdevtools
      - name: Create the necessary RPM build directories
        run: mkdir -p ~/rpmbuild/SOURCES/
      - name: Copy interal source files
        run: cp ${GITHUB_WORKSPACE}/playtron-os-scripts/* ~/rpmbuild/SOURCES/
      - name: Download external source files
        run: spectool -g -R ${GITHUB_WORKSPACE}/playtron-os-scripts/*.spec
      - name: Build the source RPM
        run: rpmbuild -bs ${GITHUB_WORKSPACE}/playtron-os-scripts/*.spec
      - name: Create the local configuration directory
        run: mkdir ~/.config/
      - name: Create the copr-cli configuration file
        run: |
          cat <<EOF > ~/.config/copr
          [copr-cli]
          login = ${FEDORA_COPR_LOGIN}
          username = playtron
          token = ${FEDORA_COPR_TOKEN}
          copr_url = https://copr.fedorainfracloud.org
          EOF
      - name: Upload the source RPM to Fedora Copr
        run: copr-cli build gaming ~/rpmbuild/SRPMS/playtron-os-scripts-*.src.rpm
