---
name: Test playtron-os-scripts
on:
  push:
    branches:
      - !main
    paths:
      - 'playtron-os-scripts/**'
jobs:
  test:
    name: Test playtron-os-scripts RPM build
    runs-on: ubuntu-22.04
    container:
      image: fedora:38
    steps:
      - uses: actions/checkout@v3
      - name: Install RPM build dependencies
        run: dnf install -y copr-cli rpm-build rpmdevtools
      - name: Create the necessary RPM build directories
        run: mkdir -p ~/rpmbuild/SOURCES/
      - name: Copy interal source files
        run: cp ${GITHUB_WORKSPACE}/playtron-os-scripts/* ~/rpmbuild/SOURCES/
      - name: Download external source files
        run: spectool -g -R ${GITHUB_WORKSPACE}/playtron-os-scripts/*.spec
      - name: Build the source RPM
        run: rpmbuild -bs ${GITHUB_WORKSPACE}/playtron-os-scripts/*.spec
      - name: Install the DNF build dependencies plugin
        run: dnf -y install 'dnf-command(builddep)'
      - name: Install the required build dependencies.
        run: dnf builddep -y ${GITHUB_WORKSPACE}/playtron-os-scripts/playtron-os-scripts.spec
      - name: Build the binary RPM
        run: rpmbuild -bb ${GITHUB_WORKSPACE}/playtron-os-scripts/playtron-os-scripts.spec
      - name: Install RPMs
        run: dnf -y install ~/rpmbuild/RPMS/*/*.rpm
